/**
 *
 * This file is autogenerated, any changes here will be overwrited by calling
 * yarn generate:icon
 *
 * **/

import React from 'react'
import { ViewStyle } from 'react-native'
import { Color, SvgProps } from 'react-native-svg'

import Box from './assets/box.svg'

interface SVGRProps {
  strokeInverted?: Color
  fillInverted?: Color
}

interface Colors {
  color?: string
  stroke?: string
  colorInverted?: string
  strokeInverted?: string
}

export interface LogoProps extends Colors {
  height?: number
  width?: number | string
  style?: ViewStyle & Colors
}

function icon(Logo: React.FC<SvgProps & SVGRProps>) {
  return function (props: LogoProps) {
    return (
      <Logo
        fill={props.color || props.style?.color}
        fillInverted={props.colorInverted}
        height={props.height || props.style?.height}
        stroke={props.stroke || props.style?.stroke}
        strokeInverted={props.strokeInverted}
        style={props.style}
        width={props.width || props.style?.width}
      />
    )
  }
}

export const svgIcons = {
  Box: icon(Box),
}
