import { StyleSheet } from 'react-native'

export const viewStyles = StyleSheet.create({
  selfBaseline: { alignSelf: 'baseline' },
  textBold: { fontWeight: 'bold' },
  noGrow: { flexGrow: 0 },
  row: { flexDirection: 'row' },
  rowCenter: { flexDirection: 'row', textAlign: 'center', alignItems: 'center', justifyContent: 'center' },
  column: { flexDirection: 'column' },
  center: { textAlign: 'center', alignItems: 'center', justifyContent: 'center' },
  noOpacity: { opacity: 0 },
  alignStart: { alignItems: 'flex-start' },
  justifyStart: { justifyContent: 'flex-start' },
  alignEnd: { alignItems: 'flex-end' },
  flexJustifyEnd: { flex: 1, justifyContent: 'flex-end' },
  selfCenter: { alignSelf: 'center' },
  noBorder: { borderWidth: 0 },
  noMarginTop: { marginTop: 0 },
  fullWidth: { width: '100%' },
  flex: { flex: 1 },
  noFlex: { flex: 0 },
  zIndexNegative: { zIndex: -1 },
  textUppercase: { textTransform: 'uppercase' },
  flexGrow: { flex: 1, flexGrow: 1 },
  grow: { flexGrow: 1 },
  absolute: { position: 'absolute' },
  flexText: { flexWrap: 'wrap', flex: 1 },
  spaceBetween: { justifyContent: 'space-between' },
  rowSpaceBetween: { flexDirection: 'row', justifyContent: 'space-between' },
  alignCenter: { alignItems: 'center' },
  wrap: { flexWrap: 'wrap' },
  rowWrap: { flexDirection: 'row', flexWrap: 'wrap' },
  justifyCenter: { justifyContent: 'center' },
  shrink: { flexShrink: 1 },
  flexAspect: { flex: 1, aspectRatio: 1 },
  selfStart: { alignSelf: 'flex-start' },
  spaceAround: { justifyContent: 'space-around' },
  absoluteFill: { position: 'absolute', top: 0, bottom: 0, start: 0, end: 0 },
  wrapContent: { alignSelf: 'baseline' },
  strike: { textDecorationLine: 'line-through' },
  selfStretch: { alignSelf: 'stretch' },
})
